### ISSUE TITLE
Can't use it with Laravel 5.1.19

### ISSUE THREAD

**Issue by pixelpeter** [mayoz/eloquent-filterable#1]
Composer won't install `eloquent-filterable` because of failing dependency for `illuminate/database`

To be able to use your library with Laravel 5.1.19 I needed to crank up the version number in `composer.json`to `"illuminate/database": "~5.2"`

No issues so far in my application

**Comment by mayoz** [comment]
Upgrade `composer.json` for latest 5.1.23 (LTS). Please use `2.0.*` version.
